/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STM32_L0538xx.h"
#include "gpio_driver.h"
#include "uart_driver.h"


int main(void)
{
	/* Enable GPIOA clock */
	RCC->IOPENR |= (1 << 0);

	/* Configure PA9 (TX) as AF4, PA10 (RX) as AF4 */
	GPIOA->MODER &= ~((3 << (9 * 2)) | (3 << (10 * 2)));   // Clear bits
	GPIOA->MODER |= ((2 << (9 * 2)) | (2 << (10 * 2)));    // AF mode
	GPIOA->AFRH &= ~((0xF << ((9 - 8) * 4)) | (0xF << ((10 - 8) * 4)));  // clear bits
	GPIOA->AFRH |=  ((4 << ((9 - 8) * 4)) | (4 << ((10 - 8) * 4)));      // AF4 (USART1)

	/* Initialize UART1 (baudrate = 9600, PCLK = 32 MHz) */
	/* ====== 3. Enable USART1 Clock ====== */
	USART1_PCLK_EN();

	/* ====== 4. Configure UART Handle ====== */
	UART_Handle_t huart1;
	huart1.pUSARTx = USART1;
	huart1.Init.BaudRate   = 9600;
	huart1.Init.WordLength = 0;    // 8-bit
	huart1.Init.StopBits   = 0;    // 1 stop bit
	huart1.Init.Parity     = 0;    // No parity
	huart1.Init.Mode       = 3;    // TX + RX

	/* ====== 5. Initialize UART ====== */
	UART_Init(&huart1);

	uint8_t txData[] = "HELLO\r\n";
	uint8_t rxData = 0;
	/* Send data repeatedly */
	while (1)
	{
		UART_SendData(&huart1, txData, 7);     // Transmit
		UART_ReceiveData(&huart1, &rxData, 1); // Receive one byte

		if (rxData == 'H')
		{
			GPIOA->MODER |= (1 << (5 * 2)); // Make PA5 output
			GPIOA->ODR ^= (1 << 5);         // Toggle LED
		}

		for (volatile uint32_t i = 0; i < 1000000; i++);
	}
}
