/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32l.h"
#include "uart_int_driver.h"

void SystemClock_Config(void);

int main(void)
{
    SystemClock_Config();                 // Set system clock to 32 MHz
    USART1_Init(115200);                  // Init UART1 @115200 baud
    USART1_EnableInterrupt();             // Enable RX interrupt
    USART1_SendString("UART Interrupt Ready\r\n");

    while (1)
    {
    }
}

/* Simple system clock setup: 32 MHz using HSI */
void SystemClock_Config(void)
{
    RCC->CR |= (1U << 0);                 // HSI16 ON
    while (!(RCC->CR & (1U << 2)));       // Wait until HSI16 ready
    RCC->CFGR |= (1U << 0);               // HSI16 as system clock
}
