/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "I2c_driver.h"
#include "STM32_L0538xx.h"
#include "gpio_driver.h"
#include <stddef.h>

I2C_Handle_t hi2c1;
I2C_DMA_Handle_t hdma_i2c1_tx;
GPIO_Config_t i2c_gpio;

/* DMA complete flag */
volatile uint8_t dma_tx_done = 0;

/* Callback overrides */
void I2C_DMA_TxCpltCallback(I2C_Handle_t *hi2c)
{
    dma_tx_done = 1;
}

int main(void)
{
    /* ----------------- GPIO CONFIG ----------------- */
    RCC->IOPENR |= (1 << 1);   // Enable GPIOB clock

    i2c_gpio.Mode = GPIO_MODE_ALTFN;
    i2c_gpio.AltFunc = 1;       // AF1 for I2C1
    i2c_gpio.Pull = GPIO_NOPULL;
    i2c_gpio.Speed = GPIO_SPEED_HIGH;

    i2c_gpio.PinNumber = GPIO_PIN_6;   // SCL
    GPIO_Init(GPIOB, &i2c_gpio);

    i2c_gpio.PinNumber = GPIO_PIN_7;   // SDA
    GPIO_Init(GPIOB, &i2c_gpio);

    /* ----------------- I2C CONFIG ----------------- */
    hi2c1.Instance = I2C1;
    hi2c1.Init.ClockSpeed = 100000;
    hi2c1.Init.AddressMode = I2C_7BIT_ADDR;
    hi2c1.Init.OwnAddress = 0x52;
    I2C_Init(&hi2c1);

    /* ----------------- DMA CONFIG ----------------- */
    RCC->AHBENR |= RCC_AHBENR_DMA1EN;  // Enable DMA1 clock

    hdma_i2c1_tx.Instance = DMA1;  // DMA controller
    hdma_i2c1_tx.Channel = 2;      // Example: I2C1_TX usually uses Channel 2
    hdma_i2c1_tx.Buffer = NULL;    // Will assign later
    hdma_i2c1_tx.Length = 0;

    uint8_t data[] = "HELLO";
    uint8_t slaveAddr = 0x08;

    /* ----------------- MAIN LOOP ----------------- */
    while (1)
    {
        dma_tx_done = 0;

        /* Prepare DMA TX buffer */
        hdma_i2c1_tx.Buffer = data;
        hdma_i2c1_tx.Length = sizeof(data) - 1;

        /* Enable I2C + DMA mode */
        I2C_DMA_Init(&hi2c1, &hdma_i2c1_tx, I2C_DMA_TX);

        /* Start I2C write */
        I2C_Start(&hi2c1, slaveAddr, I2C_WRITE);

        /* Start DMA transfer */
        I2C_DMA_Start(&hi2c1, &hdma_i2c1_tx);

        /* Wait for DMA completion */
        while (!dma_tx_done);

        /* Stop DMA and I2C */
        I2C_DMA_Stop(&hi2c1, &hdma_i2c1_tx);
        I2C_Stop(&hi2c1);

        for (volatile int i = 0; i < 100000; i++);
    }
}

/* ----------------- DMA1 Channel2 IRQ Handler ----------------- */
void DMA1_Channel2_3_IRQHandler(void)
{
    I2C_DMA_IRQHandler(&hi2c1, &hdma_i2c1_tx);
}
